"""empty message

Revision ID: 3e1fad9ad4a2
Revises: 
Create Date: 2025-02-12 20:52:25.926572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1fad9ad4a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('raciones', sa.Integer(), nullable=True),
    sa.Column('tiempo', sa.Integer(), nullable=True),
    sa.Column('pasos', sa.String(length=1000), nullable=True),
    sa.Column('es_publicada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franjas_horarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('dia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['dias.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=9), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('incidencias')
    op.drop_table('trabajadores')
    op.drop_table('franjas_horarias')
    op.drop_table('roles')
    op.drop_table('recetas')
    op.drop_table('horarios')
    op.drop_table('empresas')
    op.drop_table('dias')
    # ### end Alembic commands ###
